# Generated by Django 4.1.7 on 2023-03-29 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('billId', models.AutoField(primary_key=True, serialize=False)),
                ('generatedDate', models.DateField()),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('contactNumber', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='medicalShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopName', models.CharField(max_length=50)),
                ('shopTelephoneNo', models.CharField(max_length=10)),
                ('shopSupervisior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MedicalShop', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medName', models.CharField(max_length=100)),
                ('medDes', models.TextField()),
                ('medPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('medType', models.CharField(max_length=20)),
                ('minimumQty', models.IntegerField()),
                ('relatedShop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine', to='Medical.medicalshop')),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('batchId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('arrivalDate', models.DateField()),
                ('relatedCompany', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Medical.company')),
                ('relatedShop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='Medical.medicalshop')),
            ],
        ),
        migrations.CreateModel(
            name='stockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expiryDate', models.DateField()),
                ('batchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockItems', to='Medical.stock')),
                ('medName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medical.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='staffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffName', models.CharField(max_length=50)),
                ('mobileNo', models.CharField(max_length=10)),
                ('salary', models.IntegerField()),
                ('relatedShop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffMember', to='Medical.medicalshop')),
            ],
        ),
        migrations.CreateModel(
            name='billItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('medName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Medical.medicalshop')),
                ('relatedbill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medical.bill')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='relatedShop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medical.medicalshop'),
        ),
    ]
