# Generated by Django 4.1.7 on 2023-04-03 06:12

import Medical.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('billId', models.AutoField(primary_key=True, serialize=False)),
                ('generatedDate', models.DateTimeField(default=datetime.datetime.now)),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('contactNumber', phonenumber_field.modelfields.PhoneNumberField(help_text='Enter number with country code like +91', max_length=128, region=None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopName', models.CharField(max_length=50)),
                ('shopContactNo', phonenumber_field.modelfields.PhoneNumberField(help_text='Enter number with country code like +91', max_length=128, region=None, unique=True)),
                ('shopAddress', models.TextField(max_length=128)),
                ('shopSupervisior', models.ForeignKey(on_delete=models.SET(Medical.models.get_superuser), related_name='MedicalShops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('medName', models.CharField(max_length=100)),
                ('medDes', models.TextField()),
                ('medPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medType', models.CharField(choices=[('TB', 'Tablet'), ('CP', 'Capsule'), ('LQ', 'Liquid'), ('CR', 'Cream'), ('PC', 'Patche'), ('OT', 'Other')], default='OT', max_length=2)),
                ('minimumQty', models.IntegerField(default=10)),
                ('medImage', models.ImageField(blank=True, default='../static/images/defMedImage.jpg', null=True, upload_to='medicineImages/')),
                ('medCompany', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Medical.company')),
                ('medShop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Medicines', to='Medical.medicalshop')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('data', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderedQuantity', models.IntegerField()),
                ('currentQuantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arrivalDate', models.DateTimeField(default=datetime.datetime.now)),
                ('expiryDate', models.DateField(default=datetime.date.today)),
                ('companyName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Stocks', to='Medical.company')),
                ('medName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Stocks', to='Medical.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffName', models.CharField(max_length=50)),
                ('mobileNo', phonenumber_field.modelfields.PhoneNumberField(help_text='Enter number with country code like +91', max_length=128, region=None, unique=True)),
                ('salary', models.IntegerField()),
                ('medShop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StaffMembers', to='Medical.medicalshop')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePhoto', models.ImageField(blank=True, default='../static/images/User-Icon.jpg', null=True, upload_to='profile/')),
                ('mobileNo', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter number with country code like +91', max_length=128, null=True, region=None, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Bills', to='Medical.medicine')),
                ('relatedbill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BillItems', to='Medical.bill')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='medShop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bills', to='Medical.medicalshop'),
        ),
    ]
