# Generated by Django 4.1.7 on 2023-04-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
