# Generated by Django 4.1.7 on 2023-04-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medical', '0002_rename_description_company_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default='supervisor', max_length=15),
            preserve_default=False,
        ),
    ]
