# Generated by Django 4.1.7 on 2023-04-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medical', '0003_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePhoto',
            field=models.ImageField(blank=True, default='../static/images/User-Icon.jpg', upload_to='profile/'),
        ),
    ]
