# Generated by Django 4.1.7 on 2023-04-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medical', '0004_alter_profile_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medImage',
            field=models.ImageField(blank=True, default='../static/images/defMedImage.jpg', upload_to='medicineImages/'),
        ),
    ]
