# Generated by Django 4.1.7 on 2023-03-29 14:28

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Medical', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobileNo',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='contactNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='medicalshop',
            name='shopTelephoneNo',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilePhoto',
            field=models.ImageField(blank=True, default='static/images/defaultProfilePicture.webp', null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='mobileNo',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
