# Generated by Django 4.1.7 on 2023-03-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medical', '0005_profile_mobileno_alter_company_contactnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePhoto',
            field=models.ImageField(blank=True, default='../static/images/defaultProfilePicture.webp', null=True, upload_to='profile/'),
        ),
    ]
