# Generated by Django 4.1.7 on 2023-04-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medical', '0005_alter_medicine_medimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Supervisor', 'Supervisor')], default='Owner', max_length=11),
        ),
    ]
