# Generated by Django 4.1.7 on 2023-04-15 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Medical', '0006_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalshop',
            name='shopSupervisior',
        ),
        migrations.AddField(
            model_name='medicalshop',
            name='shopOwner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='MedicalShop', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalshop',
            name='shopSupervisor',
            field=models.ForeignKey(default=1, on_delete=models.SET(models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MedicalShop', to=settings.AUTH_USER_MODEL)), related_name='MedicalShops', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
