# Generated by Django 4.1.7 on 2023-03-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medical', '0006_alter_profile_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePhoto',
            field=models.ImageField(blank=True, default='../static/images/User-Icon.jpg', null=True, upload_to='profile/'),
        ),
    ]
