# Generated by Django 4.1.7 on 2023-04-15 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Medical', '0007_remove_medicalshop_shopsupervisior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalshop',
            name='shopSupervisor',
            field=models.OneToOneField(on_delete=models.SET(models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MedicalShop', to=settings.AUTH_USER_MODEL)), related_name='MedicalShops', to=settings.AUTH_USER_MODEL),
        ),
    ]
