# Generated by Django 4.1.7 on 2023-03-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medical', '0008_medicine_medimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medImage',
            field=models.ImageField(blank=True, default='../static/images/defMedImage.jpg', null=True, upload_to='medicineImages/'),
        ),
    ]
