# Generated by Django 4.1.7 on 2023-03-30 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Medical', '0009_alter_medicine_medimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='medName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Medical.medicine'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='medName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Medical.medicine'),
        ),
    ]
