# Generated by Django 4.1.7 on 2023-03-30 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Medical', '0010_alter_billitem_medname_alter_stockitem_medname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='relatedShop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bills', to='Medical.medicalshop'),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='medName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Bills', to='Medical.medicine'),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='relatedbill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BillItems', to='Medical.bill'),
        ),
        migrations.AlterField(
            model_name='medicalshop',
            name='shopSupervisior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MedicalShops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='relatedShop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Medicines', to='Medical.medicalshop'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='relatedShop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StaffMembers', to='Medical.medicalshop'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='relatedCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Stock', to='Medical.company'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='relatedShop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Stock', to='Medical.medicalshop'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='batchId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StockItems', to='Medical.stock'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='medName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='StockItems', to='Medical.medicine'),
        ),
    ]
