# Generated by Django 4.1.7 on 2023-03-30 10:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Medical', '0011_alter_bill_relatedshop_alter_billitem_medname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='relatedShop',
            new_name='medShop',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='relatedShop',
            new_name='medShop',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='relatedCompany',
            new_name='medCompany',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='relatedShop',
            new_name='medShop',
        ),
        migrations.AddField(
            model_name='medicalshop',
            name='shopAddress',
            field=models.TextField(default='Gujarat', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='medCompany',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Medical.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='generatedDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medType',
            field=models.CharField(choices=[('TB', 'Tablet'), ('CP', 'Capsule'), ('LQ', 'Liquid'), ('CR', 'Cream'), ('PC', 'Patche'), ('OT', 'Other')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='minimumQty',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='arrivalDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
