# Generated by Django 4.1.7 on 2023-04-24 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Medical', '0011_stockitem_medshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='medShop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Medical.medicalshop'),
            preserve_default=False,
        ),
    ]
