# Generated by Django 4.1.7 on 2023-03-30 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medical', '0012_rename_relatedshop_bill_medshop_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffmember',
            old_name='relatedShop',
            new_name='medShop',
        ),
    ]
