# Generated by Django 4.1.7 on 2023-03-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medical', '0013_rename_relatedshop_staffmember_medshop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalshop',
            old_name='shopTelephoneNo',
            new_name='shopContactNo',
        ),
        migrations.AlterField(
            model_name='medicalshop',
            name='shopName',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
