# Generated by Django 4.1.7 on 2023-03-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medical', '0014_rename_shoptelephoneno_medicalshop_shopcontactno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalshop',
            name='shopName',
            field=models.CharField(max_length=50),
        ),
    ]
