# Generated by Django 4.1.7 on 2023-03-30 12:04

import Medical.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Medical', '0016_alter_bill_totalamount_alter_billitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='medName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Bills', to='Medical.medicine'),
        ),
        migrations.AlterField(
            model_name='medicalshop',
            name='shopSupervisior',
            field=models.ForeignKey(on_delete=models.SET(Medical.models.get_superuser), related_name='MedicalShops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='medName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='StockItems', to='Medical.medicine'),
        ),
    ]
