# Generated by Django 4.1.7 on 2023-03-30 12:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Medical', '0017_alter_billitem_medname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='medExpDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='medQuantity',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billitem',
            name='medName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Bills', to='Medical.medicine'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='medName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='StockItems', to='Medical.medicine'),
        ),
    ]
